#!/usr/bin/python

PACKAGE_MODULE_PATH = '.'
CONFIG_FILE = '/etc/dyntftpd.conf'

import sys
sys.path.append(PACKAGE_MODULE_PATH)

from optparse import OptionParser
from ConfigParser import SafeConfigParser
from cStringIO import StringIO
import tftpy
import logging
import os
import file_ver_cmp
import filesys
import boot_label

logger = logging.getLogger('dyntftpd')

def open_newest_file(search_dir, prefix, path, match):
	prefix = prefix + '-'
	suffix = '-' + match.group(1)
	newest_fn = file_ver_cmp.find_highest_file_ver(prefix, suffix, search_dir)
	if newest_fn is not None:
		logger.info("determined newest file: %s" % newest_fn)
		return open(newest_fn, 'rb')
	else:
		return None

def hex_to_ip(hex):
	assert(len(hex) == 8)
	ip_nums = []
	i = 0
	while i < len(hex):
		num = hex[i:i + 2]
		ip_nums.append(str(int(num, 16)))
		i += 2
	return '.'.join(ip_nums)

def gen_pxelinux_cfg(path, match, global_cfg_dir, profile_dirs):
	hex_ip = match.group(1)
	ip = hex_to_ip(hex_ip)
	logger.debug('Matched "%s", which is %s' % (path, ip))
	profile_dir = os.path.join(profile_dirs, ip)

	config_space = {}
	execfile(os.path.join(profile_dir, 'boot_cfg.py'), config_space)

	kwargs = {
			'ip': ip,
			'profile_dir': profile_dir,
			'global_cfg_dir': global_cfg_dir
			}
	cfg_data = config_space['create_head_str'](**kwargs)
	for label in config_space['create_labels'](**kwargs):
		cfg_data += str(label)

	return StringIO(cfg_data)

def main():
	# Parse command-line options.
	parser = OptionParser()

	parser.add_option("-c", "--config",
					action = "store", dest = "config_file",
					help = "Configuration file",
					default = CONFIG_FILE)

	(options, args) = parser.parse_args()
	if len(args) != 0:
		parser.error("incorrect number of arguments")

	# Load configuration file.
	cf = SafeConfigParser()
	cf.read(options.config_file)

	logger.setLevel(logging.DEBUG)
	tftpy.setLogLevel(logging.INFO)

	simul_fs = filesys.SimulatedFileSystem()

	cfg_dir = cf.get('pxe_linux', 'global_cfg_dir')
	profile_dirs = cf.get('pxe_linux', 'profile_cfg_dirs')
	simul_fs.add_handler('^/pxelinux.cfg/([0-9a-fA-F]{8})$',
			lambda p, m: gen_pxelinux_cfg(p, m, cfg_dir, profile_dirs))

	image_dir = cf.get('overlay', 'image_dir')
	simul_fs.add_handler('^/vmlinuz-([^/]+)',
			lambda p, m: open_newest_file(image_dir, 'vmlinuz', p, m))
	simul_fs.add_handler('^/initrd-([^/]+)',
			lambda p, m: open_newest_file(image_dir, 'initrd', p, m))

	native_fs = tftpy.TftpNativeFileSys(cf.get('tftp', 'root'))

	fss = filesys.FileSystemStack()
	fss.add_file_sys(native_fs)
	fss.add_file_sys(simul_fs)

	server = tftpy.TftpCommonServer(fss)
	try:
		server.listen(cf.get('tftp', 'host'), cf.getint('tftp', 'port'))
	except KeyboardInterrupt:
		pass

if __name__ == '__main__':
	main()

# vim:set ft=python ts=4:
