#! /bin/sh

set -e
VER="`git tag -l | sort | tail -1 | sed -e 's,upstream/\(.*\),\1,'`"
TAR="../build-area/dyntftpd_${VER}.orig.tar.gz"
if [ ! -e "${TAR}" ]; then
	echo "Creating ${TAR} from ${VER} ..."
	git archive --format=tar --prefix=dyntftpd-${VER}/ upstream/${VER} | \
		gzip -9c > "${TAR}"
	echo "Checking in ${TAR} ..."
	pristine-tar commit "${TAR}" master
fi
